	<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fi-fi" lang="fi-fi">
<head>
  <link href="http://gmpg.org/xfn/11" rel="profile">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="Hugo 0.16" />

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
  <meta name="google-site-verification" content="npcZjxZqOw-RIBOXf3LqA-WmuV9LnJjisYTalXyh4AY" />
  <title> Bluebird: Catch &#43; Translate &middot; Nollaversio IT </title>

  
  <link rel="stylesheet" href="https://www.nollaversio.fi/blog/public/css/poole.css">
  <link rel="stylesheet" href="https://www.nollaversio.fi/blog/public/css/syntax.css">
  <link rel="stylesheet" href="https://www.nollaversio.fi/blog/public/css/hyde.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700|Abril+Fatface">

  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
  <link rel="shortcut icon" href="/favicon.png">

  
  <link href="" rel="alternate" type="application/rss+xml" title="Nollaversio IT" />
  <link rel="stylesheet" href="https://www.nollaversio.fi/blog/public/css/hybrid.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  

</head>

	<body class="">
		<div class="sidebar">
  <div class="container sidebar-sticky">
    <div class="sidebar-about">
      <a href="https://www.nollaversio.fi/blog/public/"><h1>Nollaversio IT</h1></a>
      <p class="lead">
       Nollaversio IT:n ohjelmointiin keskittyvä blogi. Aihepiireinä Laravel, Node.js, Electron ja arkkitehtuurit.
      </p>
    </div>

    <ul class="sidebar-nav">
      
      
      
      

        <li><a href="https://www.nollaversio.fi/blog/public/arkkitehtuuri">Arkkitehtuuri </a></li>
      

        <li><a href="https://www.nollaversio.fi/blog/public/laravel">Laravel </a></li>
      

        <li><a href="https://www.nollaversio.fi/blog/public/nodejs">Nodejs </a></li>
      

        <li><a href="https://www.nollaversio.fi/blog/public/vue">Vue </a></li>
      

    </ul>
    
    <p> Kaikki blogin sisältö MIT-lisenssillä.  Blogia ylläpitää <a href="http://jussihamalainen.fi" target="_blank">Jussi Hämäläinen</a>.</p>
  </div>
</div>


		<div class="content container">

			<div class="post">
			 	<h1>Bluebird: Catch &#43; Translate</h1>
			  <span class="post-date" style="margin-bottom: 4px;">Tue, Aug 23, 2016</span>
				<ul id="tags" class="tagslist">
				  
				</ul>
				<hr style="margin-top: 12px;">
			      

<p>Lupausketjuihin perustuvissa arkkitehtuureissa virhetilanteiden hallinta on helppoa. Useimmiten riittää, että asettaa sopivaan kohtaan lupausketjua <em>catch</em>-handlerin. Tuo handleri nappaa kiinni ketjun aiempien suoritusvaiheiden tuottamat virheet.</p>

<p>Bluebird tekee catch-handlerin käytöstä vieläkin kätevämpää tarjoamalla ikäänkuin automaattisen <em>virheiden ohjauksen</em> juuri oikeaan handleriin. Esim. seuraavasti:</p>

<pre><code class="language-javascript">
var jaateloKioski = /* luo */
var asiakas = /* luo */;

Promise.try(function() {
  return asiakas.valitseMaku();
})
.then(function(maku) {
  // Saattaa heittää virheen 'JaateloMakuLoppunut'
  return jaateloKioski.rakennaAnnos(maku)
})
.tap(function() {
  // Pyydä maksu
  // Saattaa heittää virheen 'EiRahaa'
  jaateloKioski.pyydaMaksu(asiakas);
})
.then(function(annos) {
  return asiakas.vastaanotaJaatelo(annos);
})
// Käsitellään virheet, kukin virhe yksitellen.
.catch(JaateloMakuLoppunut, function() {/* ...*/})
.catch(EiRahaa, function() {/* ...*/})

</code></pre>

<p>Ylläolevassa koodissa on mahdollista syntyä kaksi eri virhetyyppiä. Joko jäätelömaku on kiskalta toistaiseksi loppunut, tai asiakas havaitsee yllättäen, että hän on persaukinen.</p>

<p>Nämä kaksi eri virhettä käsitellään erikseen omissaan catch-handlereissa.</p>

<p>Mutta aina tilanne ei ole yhtä valoisa. Joskus tulee vastaan skenaario, jossa <em>kaksi eri loogista virhetyyppiä käyttävät saman tyypin virheobjektia.</em></p>

<p>Esimerkki:</p>

<pre><code class="language-javascript">
// Yksittäisen siirron maksimiaika
var maksimiSiirtoaika = 2000; // 2 sek
// Koko peliin (=pelaajaan kaikkiin siirtoihin) varattu maksimiaika
var peliAikaaJaljella = 180000; // 3 min

Promise.try(function() {
  return pelaaja.teeSiirtosi()
  .timeout(maksimiSiirtoaika)
  .timeout(peliAikaaJaljella)
})
.then(/* käsittele siirto ja vähennä peliaikaa */)
.catch(Promise.TimeoutError, function() {
  // Pelaaja ei tehnyt siirtoaan ajoissa.
  // Mutta kumpi timeout laukesi?
	
})

</code></pre>

<p>Ylläoleva esimerkki on melko suoraan koodistani. Osana peliserveriäni lupausketjun tulee tietää onko pelaaja ylittänyt <em>siirtokohtaisen aikansa</em> vai <em>pelikohtaisen aikansa</em>.</p>

<p>Ongelmana on, että molemmat ylityksen heittävät identtisen virheobjektin. Itse asiassa Bluebird-kirjasto tekee tuon heiton, joten sitä ei ole helppo edes kontrolloida.</p>

<h3 id="ratkaisu-muunna-geneerinen-virhetyyppi-domain-spesifiksi-virhetyypiksi">Ratkaisu: Muunna geneerinen virhetyyppi domain-spesifiksi virhetyypiksi</h3>

<p>Mutta voimme aina napata toisen heiton ja muuntaa (<strong>translate</strong>) sen toiseksi virhetyypiksi. Riittää, että asetamme ylimääräisen catch-handlerin sopivaan kohtaan.</p>

<pre><code class="language-javascript">
// Yksittäisen siirron maksimiaika
var maksimiSiirtoaika = 2000; // 2 sek
// Koko peliin (=pelaajaan kaikkiin siirtoihin) varattu maksimiaika
var peliAikaaJaljella = 180000; // 3 min

Promise.try(function() {
  return pelaaja.teeSiirtosi()
  .timeout(maksimiSiirtoaika)
  .catch(Promise.TimeoutError, function() {
    throw new MaksimiSiirtoAikaYlitetty();
  })
  .timeout(peliAikaaJaljella)
})
.then(/* käsittele siirto ja vähennä peliaikaa */)
.catch(Promise.TimeoutError, function() {
  // Pelaajan kokonaispeliaika umpeutui!	
})
.catch(MaksimiSiirtoAikaYlitetty, function() {
  // Pelaajan siirtokohtainen aika umpeutui!	
})

</code></pre>

<p>Yltä huomaamme, että nappaamme ensimmäisen mahdollisen TimeoutErrorin kiinni <em>juuri sopivasti</em> ennen toista kutsua, joka tuottaa myös TimeoutErrorin. Nappaamalla ensimmäisen virheen kiinni ja muuntamalla sen toiseen muotoon - eli toiseen virhetyyppiin - meidän ei tarvitse myöhemmin vaivata päätämme sen suhteen, mistä virhe lähti alunperin liikkeelle!</p>

<p>Tämä on siis <strong>catch + translate</strong> -patterni. Virhe napataan ja muunnetaan eri muotoon, ja muunnoksen jälkeen palautetaan takaisin &ldquo;putkeen&rdquo;.</p>

<p>Bluebird tarjoaa peräti juuri tätä catch+translate -tarkoitusta varten erillisen apumetodin: <strong>catchThrow()</strong>. Ylläoleva koodi menee muotoon:</p>

<pre><code class="language-javascript">
// Yksittäisen siirron maksimiaika
var maksimiSiirtoaika = 2000; // 2 sek
// Koko peliin (=pelaajaan kaikkiin siirtoihin) varattu maksimiaika
var peliAikaaJaljella = 180000; // 3 min

Promise.try(function() {
  return pelaaja.teeSiirtosi()
  .timeout(maksimiSiirtoaika)
  .catchThrow(Promise.TimeoutError, new MaksimiSiirtoAikaYlitetty())
  .timeout(peliAikaaJaljella)
})
.then(/* käsittele siirto ja vähennä peliaikaa */)
.catch(Promise.TimeoutError, function() {
  // Pelaajan kokonaispeliaika umpeutui!	
})
.catch(MaksimiSiirtoAikaYlitetty, function() {
  // Pelaajan siirtokohtainen aika umpeutui!	
})

</code></pre>

<blockquote>
<p>Loppukaneetti: Ihannearkkitehtuurissa myös siirtokohtaisen ajan ylitys muunnettaisiin domain-spesifiin virhetyyppiin. Tällöin emme lupausketjun lopussa nappaisi kiinni geneeristä TimeoutErroria lainkaan, vaan esim. KokonaisPeliAikaYlitetty-virheen.</p>
</blockquote>

			</div>

			


		</div>

  </body>
</html>
